Name: Instrumentation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macOS-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.SERVICE_PERSONAL_ACCESS_TOKEN}}
          submodules: recursive

      - name: test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew scan-framework:connectedCheck
